#!/usr/bin/env bash
set -euo pipefail
# gw-sshproxyctl.sh — v0.1.0
VERSION="0.1.2"

die(){ echo "ERROR: $*" >&2; exit 1; }
need_root(){ [[ "${EUID}" -eq 0 ]] || die "must run as root"; }

usage(){
  cat <<'EOF'
gw-sshproxyctl.sh (v0.1.0)

Usage:
  gw-sshproxyctl.sh install
  gw-sshproxyctl.sh add            <tenant> <name> <vip> <upstream_ip> [port]
  gw-sshproxyctl.sh remove-service <tenant> <name>
  gw-sshproxyctl.sh list           <tenant>
  gw-sshproxyctl.sh apply          <tenant>
  gw-sshproxyctl.sh remove         <tenant>
  gw-sshproxyctl.sh status         <tenant>

Files:
  Tenant conf:   /opt/gw-builder/tenants/<tenant>.conf
  Services CSV:  /etc/gateway/sshproxy/<tenant>/services.csv
  HAProxy cfg:   /etc/gateway/sshproxy/<tenant>/haproxy.cfg
  PID file:      /run/gw-sshproxy/<tenant>.pid

services.csv format:
  name,vip,upstream_ip,upstream_port
Example:
  remote-host,172.16.100.50,93.77.89.1,22
EOF
}

CMD="${1:-}"
TENANT="${2:-}"

conf_path(){ echo "/opt/gw-builder/tenants/${TENANT}.conf"; }
tenant_dir(){ echo "/etc/gateway/sshproxy/${TENANT}"; }
svc_csv(){ echo "$(tenant_dir)/services.csv"; }
hap_cfg(){ echo "$(tenant_dir)/haproxy.cfg"; }
pidfile(){ echo "/run/gw-sshproxy/${TENANT}.pid"; }

defaults_conf(){ echo "/etc/gateway/sshproxy/defaults.conf"; }

detect_wan_if(){
  local gwconf="/opt/gw-builder/gw.conf"
  [[ -f "$gwconf" ]] || return 0
  local wan
  wan="$(grep -E '^WAN_IF=' "$gwconf" | tail -n1 | cut -d= -f2- | tr -d '"' || true)"
  echo "$wan"
}

read_default_egress_if(){
  local f
  f="$(defaults_conf)"
  [[ -f "$f" ]] || return 0
  grep -E '^SSH_PROXY_EGRESS_IF_DEFAULT=' "$f" | tail -n1 | cut -d= -f2- || true
}

write_default_egress_if(){
  local eif="$1"
  mkdir -p /etc/gateway/sshproxy
  echo "SSH_PROXY_EGRESS_IF_DEFAULT=${eif}" > "$(defaults_conf)"
}

ensure_tenant_egress_if(){
  # If tenant conf does not specify SSH_PROXY_EGRESS_IF, set it from defaults.conf (if present).
  local tconf eif
  tconf="$(conf_path)"
  [[ -f "$tconf" ]] || return 0
  if grep -q '^SSH_PROXY_EGRESS_IF=' "$tconf"; then
    return 0
  fi
  eif="$(read_default_egress_if || true)"
  [[ -n "$eif" ]] || return 0
  echo "SSH_PROXY_EGRESS_IF=${eif}" >> "$tconf"
}

getv(){
  local k="$1"
  grep -E "^${k}=" "$(conf_path)" 2>/dev/null | tail -n1 | cut -d= -f2- || true
}

vrf_name(){
  local v
  v="$(getv TENANT_VRF)"
  [[ -n "$v" ]] && { echo "$v"; return; }
  echo "vrf-${TENANT}"
}

dummy_iface(){ echo "sshvip-${TENANT}"; }

ensure_dirs(){
  mkdir -p "$(tenant_dir)"
  mkdir -p /run/gw-sshproxy
  if [[ ! -f "$(svc_csv)" ]]; then
    echo "name,vip,upstream_ip,upstream_port" > "$(svc_csv)"
  fi
}

emit_allowlist() {
  # Derive unique upstream IPs from services.csv and write to tenant conf:
  #   SSH_PROXY_UPSTREAM_ALLOWLIST=ip1,ip2,...
  local ips
  ips="$(tail -n +2 "$(svc_csv)" 2>/dev/null | awk -F',' '{gsub(/[[:space:]]/,"",$3); if($3!="") print $3}' | sort -u | paste -sd, -)"
  [[ -n "$ips" ]] || return 0
  local tconf
  tconf="$(conf_path)"
  [[ -f "$tconf" ]] || return 0
  if grep -q '^SSH_PROXY_UPSTREAM_ALLOWLIST=' "$tconf"; then
    sed -i "s/^SSH_PROXY_UPSTREAM_ALLOWLIST=.*/SSH_PROXY_UPSTREAM_ALLOWLIST=${ips}/" "$tconf"
  else
    echo "SSH_PROXY_UPSTREAM_ALLOWLIST=${ips}" >> "$tconf"
  fi
}


render_haproxy(){
  local cfg
  cfg="$(hap_cfg)"

  cat >"$cfg" <<EOF
# haproxy.cfg tenant ${TENANT} — generated by gw-sshproxyctl v${VERSION}
global
  daemon
  maxconn 4096
  log stdout format raw local0

defaults
  mode tcp
  log global
  option tcplog
  timeout connect 10s
  timeout client  1h
  timeout server  1h
EOF

  tail -n +2 "$(svc_csv)" | while IFS=',' read -r name vip up_ip up_port; do
    name="$(echo "$name" | xargs)"
    vip="$(echo "$vip" | xargs)"
    up_ip="$(echo "$up_ip" | xargs)"
    up_port="$(echo "${up_port:-22}" | xargs)"
    [[ -n "$name" && -n "$vip" && -n "$up_ip" ]] || continue

    cat >>"$cfg" <<EOF

frontend fe_${name}
  bind ${vip}:22
  default_backend be_${name}

backend be_${name}
  server s1 ${up_ip}:${up_port} check
EOF
  done
}

vip_apply(){
  local iface vrf
  iface="$(dummy_iface)"
  vrf="$(vrf_name)"

  if ! ip link show "$iface" >/dev/null 2>&1; then
    ip link add "$iface" type dummy
  fi
  ip link set "$iface" master "$vrf" 2>/dev/null || true
  ip link set "$iface" up

  tail -n +2 "$(svc_csv)" | while IFS=',' read -r name vip up_ip up_port; do
    vip="$(echo "$vip" | xargs)"
    [[ -n "$vip" ]] || continue
    if ! ip addr show dev "$iface" | grep -q "\b${vip}/32\b"; then
      ip addr add "${vip}/32" dev "$iface"
    fi
  done
}

vip_remove(){
  local iface
  iface="$(dummy_iface)"
  if ip link show "$iface" >/dev/null 2>&1; then
    ip addr show dev "$iface" | awk '/inet / {print $2}' | while read -r cidr; do
      ip addr del "$cidr" dev "$iface" 2>/dev/null || true
    done
    ip link set "$iface" down 2>/dev/null || true
    ip link del "$iface" 2>/dev/null || true
  fi
}

start_haproxy(){
  command -v haproxy >/dev/null 2>&1 || die "haproxy not installed"
  stop_haproxy || true
  haproxy -f "$(hap_cfg)" -p "$(pidfile)"
}

stop_haproxy(){
  if [[ -f "$(pidfile)" ]]; then
    pid="$(cat "$(pidfile)" 2>/dev/null || true)"
    [[ -n "$pid" ]] && kill "$pid" 2>/dev/null || true
    rm -f "$(pidfile)"
  fi
  pkill -f "haproxy -f $(hap_cfg)" 2>/dev/null || true
}

status_haproxy(){
  if [[ -f "$(pidfile)" ]]; then
    pid="$(cat "$(pidfile)" 2>/dev/null || true)"
    echo "haproxy pid=${pid:-unknown}"
    ps -p "${pid:-0}" -o pid,cmd 2>/dev/null || true
  else
    echo "haproxy not running"
  fi
}

cmd_install(){
  need_root
  prefix="/opt/gw-sshproxy"
  mkdir -p "$prefix"
  install -m 0755 "$(realpath "$0")" "$prefix/gw-sshproxyctl.sh"
  install -m 0644 "$(dirname "$(realpath "$0")")/README.txt" "$prefix/README.txt"

  # v0.1.2: set SSH_PROXY_EGRESS_IF_DEFAULT from GW WAN_IF (or prompt)
  local wan
  wan="$(detect_wan_if || true)"
  if [[ -z "$wan" ]]; then
    read -r -p "Default SSH proxy egress interface (from GW WAN_IF, e.g. eth0): " wan
  fi
  if [[ -n "$wan" ]]; then
    write_default_egress_if "$wan"
    echo "Set SSH_PROXY_EGRESS_IF_DEFAULT=$wan in $(defaults_conf)"
  else
    echo "WARN: No default egress IF set; set SSH_PROXY_EGRESS_IF in each tenant conf for enforcement."
  fi

  echo "Installed to $prefix"
}

cmd_add(){
  need_root
  name="${3:-}"; vip="${4:-}"; up="${5:-}"; port="${6:-22}"
  [[ -n "$TENANT" && -n "$name" && -n "$vip" && -n "$up" ]] || die "Usage: add <tenant> <name> <vip> <upstream_ip> [port]"
  [[ -f "$(conf_path)" ]] || die "tenant conf not found: $(conf_path)"
  ensure_dirs
  tmp="$(mktemp)"
  awk -F',' -v n="$name" 'NR==1 || $1!=n' "$(svc_csv)" > "$tmp"
  mv "$tmp" "$(svc_csv)"
  echo "${name},${vip},${up},${port}" >> "$(svc_csv)"
  echo "Added: $name $vip -> $up:$port"
}

cmd_remove_service(){
  need_root
  name="${3:-}"
  [[ -n "$TENANT" && -n "$name" ]] || die "Usage: remove-service <tenant> <name>"
  ensure_dirs
  tmp="$(mktemp)"
  awk -F',' -v n="$name" 'NR==1 || $1!=n' "$(svc_csv)" > "$tmp"
  mv "$tmp" "$(svc_csv)"
  echo "Removed: $name"
}

cmd_list(){
  [[ -n "$TENANT" ]] || die "tenant required"
  ensure_dirs
  column -t -s, "$(svc_csv)" || cat "$(svc_csv)"
}

cmd_apply(){
  need_root
  [[ -n "$TENANT" ]] || die "tenant required"
  [[ -f "$(conf_path)" ]] || die "tenant conf not found: $(conf_path)"
  ensure_dirs
  ensure_tenant_egress_if
  emit_allowlist
  render_haproxy
  vip_apply
  start_haproxy
  echo "Applied ssh proxy tenant=$TENANT"
}

cmd_remove(){
  need_root
  [[ -n "$TENANT" ]] || die "tenant required"
  ensure_dirs
  stop_haproxy || true
  vip_remove || true
  echo "Removed ssh proxy tenant=$TENANT"
}

cmd_status(){
  [[ -n "$TENANT" ]] || die "tenant required"
  echo "tenant=$TENANT vrf=$(vrf_name) iface=$(dummy_iface)"
  ip link show "$(dummy_iface)" 2>/dev/null || true
  ip addr show dev "$(dummy_iface)" 2>/dev/null || true
  status_haproxy
}

case "$CMD" in
  ""|-h|--help|help) usage ;;
  install) cmd_install ;;
  add) cmd_add ;;
  remove-service) cmd_remove_service ;;
  list) cmd_list ;;
  apply) cmd_apply ;;
  remove) cmd_remove ;;
  status) cmd_status ;;
  *) die "Unknown command: $CMD" ;;
esac
