#!/usr/bin/env bash
set -euo pipefail

# v0.5.0 - Certificate enrollment/import portal (Phase 1)
# This module provides a minimal portal backend for:
# - OTP bootstrap (time-limited token)
# - CSR upload (PEM) -> sign with tenant intermediate CA -> return cert bundle
#
# Implementation choice:
# - A lightweight Flask app + gunicorn, bound to 127.0.0.1:9443 inside tenant VRF
# - NGINX terminates TLS and enforces mTLS at PORTAL_VIP:443
#
# NOTE: SAML/OIDC bootstrap is intentionally left as integration points.
# For Phase 1, OTP is generated by admins via gwctl and shared out-of-band.

PORTAL_APP_DIR="/opt/gw-builder/portal"
PORTAL_STATE_DIR="/etc/gateway/portal"
PORTAL_LOG_DIR="/var/log/gw-portal"

ensure_portal_dirs() {
  mkdir -p "${PORTAL_APP_DIR}" "${PORTAL_STATE_DIR}" "${PORTAL_LOG_DIR}"
}

write_portal_app() {
  cat >"${PORTAL_APP_DIR}/app.py" <<'PY'
import os, time, hmac, hashlib, base64, json
from flask import Flask, request, jsonify, send_file

APP = Flask(__name__)

STATE_DIR = os.environ.get("PORTAL_STATE_DIR", "/etc/gateway/portal")
TENANT = os.environ.get("PORTAL_TENANT", "unknown")

def _token_path(token: str) -> str:
    return os.path.join(STATE_DIR, TENANT, "tokens", f"{token}.json")

def _ensure_tenant_dirs():
    os.makedirs(os.path.join(STATE_DIR, TENANT, "tokens"), exist_ok=True)
    os.makedirs(os.path.join(STATE_DIR, TENANT, "issued"), exist_ok=True)

@APP.get("/healthz")
def healthz():
    return "ok\n", 200

@APP.get("/whoami")
def whoami():
    # NGINX passes identity headers from mTLS
    return jsonify({
        "tenant": TENANT,
        "mtls_verify": request.headers.get("X-mTLS-Verify"),
        "mtls_dn": request.headers.get("X-mTLS-DN"),
        "mtls_fingerprint": request.headers.get("X-mTLS-Fingerprint"),
    })

@APP.post("/enroll/sign-csr")
def sign_csr():
    """
    Phase 1 endpoint:
    - requires OTP token (query param or header)
    - requires email (json) and CSR (PEM, in request body or json field)
    - portal validates token (one-time, TTL)
    - invokes local openssl signing wrapper (called by gwctl) via filesystem drop
    This app is intentionally minimal; it writes a request file and expects a sidecar signer to fulfill it.
    """
    _ensure_tenant_dirs()
    token = request.args.get("token") or request.headers.get("X-OTP-Token")
    if not token:
        return jsonify({"error":"missing token"}), 400

    tp = _token_path(token)
    if not os.path.exists(tp):
        return jsonify({"error":"invalid token"}), 403

    meta = json.load(open(tp, "r"))
    now = int(time.time())
    if meta.get("used"):
        return jsonify({"error":"token already used"}), 403
    if now > int(meta["exp"]):
        return jsonify({"error":"token expired"}), 403

    payload = request.get_json(silent=True) or {}
    email = payload.get("email") or request.args.get("email")
    csr_pem = payload.get("csr_pem")
    if not email or not csr_pem:
        return jsonify({"error":"need email and csr_pem"}), 400

    # mark used
    meta["used"] = True
    meta["used_ts"] = now
    json.dump(meta, open(tp, "w"))

    # write signing request for out-of-process signer
    rid = f"{now}-{hashlib.sha256((email+token).encode()).hexdigest()[:16]}"
    req_dir = os.path.join(STATE_DIR, TENANT, "issued", rid)
    os.makedirs(req_dir, exist_ok=True)
    open(os.path.join(req_dir, "email.txt"), "w").write(email + "\n")
    open(os.path.join(req_dir, "request.csr.pem"), "w").write(csr_pem + "\n")

    return jsonify({
        "status":"accepted",
        "request_id": rid,
        "next": f"/enroll/download?request_id={rid}"
    }), 202

@APP.get("/enroll/download")
def download():
    """
    Downloads the signed bundle once signer has produced it:
    - cert.pem
    - chain.pem
    - key.pem (optional; typically client keeps key; for Phase 1 we allow server-side generation later)
    - bundle.p12 (optional)
    """
    rid = request.args.get("request_id")
    if not rid:
        return jsonify({"error":"missing request_id"}), 400
    req_dir = os.path.join(STATE_DIR, TENANT, "issued", rid)
    bundle = os.path.join(req_dir, "bundle.zip")
    if not os.path.exists(bundle):
        return jsonify({"error":"not ready"}), 404
    return send_file(bundle, as_attachment=True, download_name=f"{TENANT}-{rid}-bundle.zip")

if __name__ == "__main__":
    APP.run(host="127.0.0.1", port=9443)
PY

  cat >"${PORTAL_APP_DIR}/requirements.txt" <<'EOF'
flask==3.0.3
gunicorn==22.0.0
EOF
}

write_portal_systemd() {
  mkdir -p /etc/systemd/system
  cat >/etc/systemd/system/gw-portal@.service <<'EOF'
[Unit]
Description=gw-builder tenant enrollment portal for %i (runs in tenant VRF)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=PORTAL_TENANT=%i
Environment=PORTAL_STATE_DIR=/etc/gateway/portal
WorkingDirectory=/opt/gw-builder/portal
# run in tenant VRF
ExecStart=/usr/sbin/ip vrf exec vrf-%i /usr/bin/gunicorn -b 127.0.0.1:9443 app:APP
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=multi-user.target
EOF
}


write_portal_signer_systemd() {
  mkdir -p /etc/systemd/system
  cat >/etc/systemd/system/gw-portal-signer@.service <<'EOF'
[Unit]
Description=gw-builder tenant portal signer worker for %i (runs in tenant VRF)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=/opt/gw-builder
ExecStart=/usr/sbin/ip vrf exec vrf-%i /opt/gw-builder/gwctl.sh portal-signer-loop %i
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=multi-user.target
EOF
}

portal_enable() {
  local tenant="$1"
  ensure_portal_dirs
  mkdir -p "${PORTAL_STATE_DIR}/${tenant}/tokens" "${PORTAL_STATE_DIR}/${tenant}/issued"
  write_portal_app
  write_portal_systemd
  write_portal_signer_systemd
  systemctl daemon-reload
  systemctl enable --now "gw-portal@${tenant}"
  systemctl enable --now "gw-portal-signer@${tenant}"
}

portal_disable() {
  local tenant="$1"
  systemctl disable --now "gw-portal@${tenant}" || true
  systemctl disable --now "gw-portal-signer@${tenant}" || true
}
